---
- name:  Config Webservers
  hosts: all
  gather_facts: true
  tasks:
  - name: Firewall configure
    firewalld:
      port: "{{ item }}"
      permanent: yes
      state: enabled
      immediate: true
    with_items:
    - 80/tcp
    - 3091/tcp
    - 8080/tcp
    when: ansible_distribution == "RedHat" and ansible_system_vendor != "Xen"

  - name: SELinux configure
    seboolean:
      name: haproxy_connect_any
      state: yes
      persistent: yes
      
  - name: Copy over the haproxy configuration
    template: 
      src: haproxy.jinja2
      dest: /etc/haproxy/haproxy.cfg
    notify:
    - restart haproxy

  - name: Copy over the apache configuration
    template: 
      src: httpd.jinja2
      dest: /etc/httpd/conf/httpd.conf
    notify:
    - restart httpd
  
  - name: Enable service httpd, haproxy
    service:
      name: "{{ item }}"
      enabled: yes
      state: started
    with_items:
      - httpd
      - haproxy     
 
  handlers:
  - name: restart httpd
    service: 
      name: httpd  
      state: restarted

  - name: restart haproxy
    service: 
      name: haproxy  
      state: restarted