---
- name: Deploy web content
  hosts: all
  tasks:
  - name: Gather the rpm package facts
    package_facts:
      manager: auto
      
  - name: Copy over the httpd index
    template: 
      src: index.jinja2
      dest: /var/www/html/index.html
    notify:
    - restart httpd
    
  handlers:
  - name: restart httpd
    service: 
      name: httpd  
      state: restarted