---
- name:  Config generic VMs
  hosts: all
  gather_facts: true
  tasks:    
  - name: Disable YUM Repo
    yum_repository:
      name: rhui-client-config-server-8
      file: redhat-rhui-client-config
      state: absent
    when: ansible_distribution == "RedHat" and ansible_system_vendor == "Xen"
    notify: yum-clean-metadata

  - name: Disable YUM Repo
    yum_repository:
      name: "{{ item }}"
      file: redhat-rhui
      state: absent
    when: ansible_distribution == "RedHat" and ansible_system_vendor == "Xen"
    with_items:
      - rhel-8-appstream-rhui-rpms
      - rhel-8-baseos-rhui-rpms
    notify: yum-clean-metadata

  - name: Install a modularity appstream with defined stream
    dnf:
      name: "@nodejs:14"
      state: present

  - name: install required packages
    package:
      name:
      - policycoreutils-python-utils
      state: present
      
  - name: Copy over the chronyd configuration
    template: 
      src: chrony.jinja2
      dest: /etc/chrony.conf
    notify:
    - restart chronyd

  handlers:
  - name: restart chronyd
    service: 
      name: chronyd  
      state: restarted
  
  - name: yum-clean-metadata
    command: yum clean metadata
    args:
      warn: no