---
- name:  Config generic VMs
  hosts: all
  tasks:
  - name: install required packages
    package:
      name:
      - chrony
      - policycoreutils-python-utils
      state: present
      
  - name: Install a modularity appstream with defined stream
    dnf:
      name: "@nodejs:14"
      state: present
      
  - name: Copy over the chronyd configuration
    template: 
      src: chrony.jinja2
      dest: /etc/chrony.conf
    notify:
    - restart chronyd

  handlers:
  - name: restart chronyd
    service: 
      name: chronyd  
      state: restarted