---
- name:  Config generic VMs
  hosts: all
  gather_facts: true
  tasks:    
  - name: Disable YUM Repo
    yum_repository:
      name: "{{ item.name }}"
      file: "{{ item.file }}"
      state: absent
    when: ansible_distribution == "RedHat" and ansible_system_vendor == "Xen"
    loop:
      - name: rhui-client-config-server-8
        file: redhat-rhui-client-config
      - name: rhel-8-appstream-rhui-rpms
        file: redhat-rhui
      - name: rhel-8-baseos-rhui-rpms
        file: redhat-rhui

  - name: install required packages
    package:
      name:
      - policycoreutils-python-utils
      - chrony
      state: present

  - name: install the latest version of VMware guess-tools
    yum:
      name: open-vm-tools
      state: latest
    when: ansible_virtualization_type == "VMware"

  - name: install the latest version of RHV guess-tools
    yum:
      name: ovirt-guest-agent-common
      state: latest
    when: ansible_virtualization_type == "kvm"
    
  - name: Copy over the chronyd configuration
    template: 
      src: chrony.jinja2
      dest: /etc/chrony.conf
    notify:
    - restart chronyd

  handlers:
  - name: restart chronyd
    service: 
      name: chronyd  
      state: restarted